"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { ChevronDown, Dices, Map, Menu, Search, Shield, Sparkles, Swords, X } from "lucide-react";
import { Race, races, regions, statLabels } from "@/lib/game-data";

const nav = [["Início", "inicio"], ["Raças", "racas"], ["Mundo", "mundo"], ["Regiões", "regioes"], ["Sistemas", "sistemas"], ["Guilda", "guilda"], ["Tabuleiro", "tabuleiro"]];
function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

function TiltCard({ race, onOpen }: { race: Race; onOpen: () => void }) {
  const ref = useRef<HTMLButtonElement>(null);
  function move(e: React.PointerEvent<HTMLButtonElement>) { const el = ref.current; if (!el) return; const r = el.getBoundingClientRect(); const x = (e.clientX-r.left)/r.width-.5; const y = (e.clientY-r.top)/r.height-.5; el.style.setProperty("--rx",`${-y*9}deg`); el.style.setProperty("--ry",`${x*11}deg`); el.style.setProperty("--mx",`${(x+.5)*100}%`); el.style.setProperty("--my",`${(y+.5)*100}%`); }
  function reset() { ref.current?.style.setProperty("--rx","0deg"); ref.current?.style.setProperty("--ry","0deg"); }
  return <button ref={ref} onPointerMove={move} onPointerLeave={reset} onClick={onOpen} className="race-card" aria-label={`Abrir ficha de ${race.name}`}>
    <Image src={`/assets/racas/raca-${race.slug}.png`} alt={`Arte de ${race.name}`} fill sizes="(max-width: 680px) 82vw, (max-width: 1100px) 40vw, 270px" />
    <span className="card-shine"/><span className="card-index">{String(races.indexOf(race)+1).padStart(2,"0")}</span>
    <span className="card-copy"><span className="eyebrow">{race.affinity} · {race.title}</span><strong>{race.name}</strong><span className="mini-stats"><b>ATQ {race.stats.atk}</b><b>DEF {race.stats.def}</b><b>VEL {race.stats.speed}</b></span></span>
  </button>;
}

function RaceModal({ race, close }: { race: Race; close: () => void }) {
  useEffect(() => { const onKey=(e:KeyboardEvent)=>e.key==="Escape"&&close(); document.body.classList.add("modal-open"); window.addEventListener("keydown",onKey); return()=>{document.body.classList.remove("modal-open");window.removeEventListener("keydown",onKey)}; },[close]);
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`Ficha de ${race.name}`} onMouseDown={e=>e.target===e.currentTarget&&close()}><article className="character-sheet">
    <button className="close-button" onClick={close} aria-label="Fechar ficha"><X size={19}/></button>
    <div className="clean-art"><Image src={`/assets/racas/raca-${race.slug}.png`} alt={race.name} fill priority sizes="(max-width: 800px) 100vw, 52vw"/></div>
    <div className="sheet-info"><p className="eyebrow">{race.affinity} · {race.title}</p><h2>{race.name}</h2><p className="lead">{race.description}</p>
      <div className="stats-grid">{Object.entries(race.stats).map(([key,value])=><div className="stat" key={key}><span>{statLabels[key as keyof typeof statLabels]}</span><b>{value}</b><i><em style={{width:`${Math.min(value,100)}%`}}/></i></div>)}</div>
      <div className="traits"><div><span>Vantagens</span>{race.bonuses.map(x=><p key={x}>+ {x.replace("+","")}</p>)}</div><div><span>Limitações</span>{race.penalties.map(x=><p key={x}>− {x.replace("−","")}</p>)}</div></div>
      <div className="story"><span>Crônica</span><p>{race.story}</p></div>
    </div></article></div>;
}

function D20() {
  const [result,setResult]=useState(20); const [rolling,setRolling]=useState(false); const [history,setHistory]=useState<number[]>([]);
  function roll(){if(rolling)return;setRolling(true);let ticks=0;const timer=window.setInterval(()=>{setResult(Math.floor(Math.random()*20)+1);if(++ticks>12){clearInterval(timer);const final=Math.floor(Math.random()*20)+1;setResult(final);setHistory(h=>[final,...h].slice(0,6));setRolling(false)}},55)}
  return <div className="dice-console"><button className={`d20 ${rolling?"rolling":""} ${result===20?"critical":""}`} onClick={roll} aria-label="Rolar dado de vinte lados"><span className="die-face"><small>D20</small><b>{result}</b></span></button>
    <div className="roll-panel"><p className="eyebrow">Dado clássico</p><h3>{rolling?"Rolando…":result===20?"Acerto crítico!":result===1?"Falha crítica":`Resultado: ${result}`}</h3><p>Clique no dado para testar seu destino. Cada resultado é gerado aleatoriamente de 1 a 20.</p><button onClick={roll} disabled={rolling}><Dices size={18}/> Rolar D20</button><div className="history">{history.map((n,i)=><span key={`${n}-${i}`}>{n}</span>)}</div></div>
  </div>;
}

export default function Home(){
  const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Race|null>(null); const [menuOpen,setMenuOpen]=useState(false);
  const filtered=useMemo(()=>races.filter(r=>`${r.name} ${r.title} ${r.affinity}`.toLowerCase().includes(query.toLowerCase())),[query]);
  return <main><header className="glass-nav"><button className="brand" onClick={()=>scrollTo("inicio")}><span className="brand-rune">R</span><span>REINO <b>ETERNO</b></span></button><nav className={menuOpen?"open":""}>{nav.map(([label,id])=><button key={id} onClick={()=>{scrollTo(id);setMenuOpen(false)}}>{label}</button>)}</nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Abrir menu"><Menu/></button></header>
    <section id="inicio" className="hero"><div className="map-background" aria-hidden="true"/><div className="aurora a1"/><div className="aurora a2"/><div className="hero-content"><p className="eyebrow"><Sparkles size={14}/> Crônicas da Primeira Aurora</p><h1>Escolha quem<br/><i>você será.</i></h1><p>Um mundo dividido entre a luz de Aurenya e a corrupção de Nozkar. Explore raças, regiões e sistemas — então deixe o D20 decidir seu destino.</p><div className="hero-actions"><button onClick={()=>scrollTo("racas")}>Explorar personagens <ChevronDown size={17}/></button><button className="ghost" onClick={()=>scrollTo("tabuleiro")}><Dices size={17}/> Rolar o dado</button></div></div><div className="world-mark"><span>Continente de Primordia</span><b>201.600 km²</b></div></section>
    <section id="racas" className="section races-section"><div className="section-head"><div><p className="eyebrow">Arquivo dos despertos</p><h2>Vinte caminhos.<br/>Uma única aurora.</h2></div><div className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar por nome, afinidade…" aria-label="Pesquisar raça"/>{query&&<button onClick={()=>setQuery("")} aria-label="Limpar pesquisa"><X size={16}/></button>}</div></div><div className="results-line"><span>{filtered.length} personagens encontrados</span><i/></div><div className="race-grid">{filtered.map(r=><TiltCard key={r.name} race={r} onOpen={()=>setSelected(r)}/>)}</div>{!filtered.length&&<div className="no-results"><Search/><h3>Nenhum herói encontrado</h3><p>Tente outro nome ou afinidade.</p></div>}</section>
    <section id="mundo" className="lore-section"><div className="lore-art"><Image src="/assets/mundo/mundo-primeira-aurora.png" alt="O mundo da Primeira Aurora" fill sizes="100vw"/></div><div className="lore-copy glass-panel"><p className="eyebrow">O mundo · Ano 847 da Aurora</p><h2>A Primeira Aurora</h2><p>Em Primordia, Aurenya mantinha a luz, a vida e o ciclo em equilíbrio com Nozkar, senhor da escuridão, da corrupção e do desespero. Quando o pacto se rompeu, a guerra abriu a Primeira Aurora.</p><p>Para selar Nozkar, Aurenya dividiu sua essência em Fragmentos da Aurora. Hoje esses fragmentos escolhem campeões mortais enquanto cultos, artefatos e criaturas anunciam que o antigo selo está cedendo.</p><div className="prophecy">“Quando a aurora se partir outra vez, não serão deuses — mas escolhas — que decidirão o fim.”</div></div></section>
    <section id="regioes" className="section region-section"><div className="section-head"><div><p className="eyebrow"><Map size={14}/> Atlas de Primordia</p><h2>Seis regiões.<br/>Nenhum caminho seguro.</h2></div><p className="section-intro">Do ouro de Luminária às trevas de Nozkar, cada território muda as regras da jornada.</p></div><div className="region-grid">{regions.map((r,i)=><article className="region-card" key={r.name}><div className="region-image"><Image src={`/assets/regioes/regiao-${r.slug}.png`} alt={r.name} fill sizes="(max-width: 800px) 90vw, 32vw"/><span>0{i+1}</span></div><div className="region-copy"><p className="eyebrow">{r.role}</p><h3>{r.name}</h3><p>{r.lore}</p><div><b>{r.size}</b><span>Perigo: {r.danger}</span></div></div></article>)}</div></section>
    <section id="sistemas" className="systems-section"><div className="systems-art"><Image src="/assets/sistemas/sistemas-base-geral.png" alt="Sistemas de combate" fill sizes="50vw"/></div><div className="systems-copy"><p className="eyebrow"><Swords size={14}/> Regras de combate</p><h2>Estratégia antes da força.</h2><p>Rodadas ordenadas por velocidade. Em cada turno, ataque, posicione-se e use uma habilidade na ordem que desejar. Sua reação é preciosa: depois de usada, leva quatro rodadas para retornar.</p><div className="system-cards"><article><b>01</b><h3>Turnos</h3><p>Controles atrasam, reduzem ou cancelam ações. Dano e cura contínuos resolvem no fim do turno.</p></article><article><b>02</b><h3>Dano</h3><p>Armadura, defesa arcana, crítico de 150%, escudos, pressão e execução criam decisões reais.</p></article><article><b>03</b><h3>Estrelas</h3><p>Seis níveis: despertar, melhoria, especialização, evolução, ascensão e habilidade definitiva.</p></article></div></div></section>
    <section id="guilda" className="section guild-section"><div className="section-head"><div><p className="eyebrow"><Shield size={14}/> Guilda dos Selos</p><h2>Contratos, reputação<br/>e recompensas.</h2></div><p className="section-intro">Aceite contratos criados pela comunidade, reúna seu grupo e converta feitos em selos cada vez mais raros.</p></div><div className="guild-grid"><article><Image src="/assets/guilda/guilda-quadro-de-missoes.png" alt="Quadro de missões" fill sizes="50vw"/><div><p className="eyebrow">Quadro vivo</p><h3>Missões da guilda</h3><p>Caçada, coleta, defesa, exploração, elite e raid. Cada contrato muda a economia e a reputação dos aventureiros.</p></div></article><article><Image src="/assets/guilda/guilda-evolucao-dos-selos.png" alt="Evolução dos selos" fill sizes="50vw"/><div><p className="eyebrow">Progressão</p><h3>Do bronze ao diamante</h3><p>Converta dez selos de um grau no próximo. Suba de E a Lendário e desbloqueie missões reservadas aos maiores nomes.</p></div></article></div></section>
    <section id="tabuleiro" className="board-section"><div className="board-copy"><p className="eyebrow"><Dices size={14}/> Mesa de campanha</p><h2>O tabuleiro está pronto.</h2><p>Posicione a companhia, trace a rota e role o dado. O resto pertence à sorte.</p></div><div className="board-stage"><div className="game-board" aria-label="Tabuleiro decorativo de RPG">{Array.from({length:64},(_,i)=><span key={i} className={(i===9||i===28||i===51)?"occupied":""}>{i===9?"♜":i===28?"♞":i===51?"✦":""}</span>)}</div><D20/></div></section>
    <footer><span className="brand-rune">R</span><p>REINO ETERNO · Crônicas da Primeira Aurora</p><button onClick={()=>scrollTo("inicio")}>Voltar ao início ↑</button></footer>{selected&&<RaceModal race={selected} close={()=>setSelected(null)}/>}</main>;
}
