export type Race = {
  name: string;
  slug: string;
  title: string;
  affinity: string;
  stats: { hp: number; atk: number; def: number; arcDef: number; speed: number; arcana: number };
  bonuses: string[];
  penalties: string[];
  description: string;
  story: string;
};

export const races: Race[] = [
  { name: "Alien", slug: "alien", title: "Errante das estrelas", affinity: "Éter", stats: { hp: 90, atk: 55, def: 45, arcDef: 70, speed: 45, arcana: 75 }, bonuses: ["+10% Arcana", "+5% Velocidade", "+5% Defesa Arcana"], penalties: ["−10% Defesa Física", "−5% Vida máxima"], description: "Seres vindos de além do firmamento, capazes de adaptar matéria e pensamento. Sua constituição é frágil, mas a mente alcança frequências que os povos de Primordia mal percebem.", story: "Quando uma estrela caiu sobre Thalenn, Ilyon despertou dentro do cristal. Desde então busca a constelação que aparece em seus sonhos — e responde aos Fragmentos da Aurora como se fossem antigos faróis." },
  { name: "Anão", slug: "anao", title: "Guardião da forja", affinity: "Pedra", stats: { hp: 120, atk: 70, def: 85, arcDef: 45, speed: 20, arcana: 40 }, bonuses: ["+10% Defesa Física", "+5% Vida", "+5% Resistência Física"], penalties: ["−10% Velocidade", "−5% Arcana"], description: "Mestres da pedra, da forja e dos juramentos. Anões suportam o peso de uma linha de frente como muralhas vivas.", story: "Borin selou a última forja de Kragor quando o titã vulcânico despertou. Agora carrega a chave no peito e procura aliados dignos de reabrir o coração da montanha." },
  { name: "Aracneano", slug: "aracneano", title: "Tecelão do véu", affinity: "Veneno", stats: { hp: 85, atk: 75, def: 50, arcDef: 45, speed: 75, arcana: 50 }, bonuses: ["+10% Precisão", "+5% Velocidade", "+5% Crítico"], penalties: ["−10% Vida", "−5% Defesa Física"], description: "Caçadores de movimentos precisos, dominam seda, venenos e emboscadas. Sua mobilidade transforma qualquer ruína em território próprio.", story: "Syra guarda um mapa tecido em seda viva. Cada fio muda quando D’Akan se move, apontando para um santuário que talvez conheça a verdadeira origem de sua espécie." },
  { name: "Celestial", slug: "celestial", title: "Arauto da aurora", affinity: "Luz", stats: { hp: 90, atk: 50, def: 50, arcDef: 70, speed: 40, arcana: 80 }, bonuses: ["+10% Cura recebida", "+5% Defesa Arcana", "+5% Resistência a controle"], penalties: ["−10% Dano Físico"], description: "Descendentes de antigos guardiões da luz, canalizam proteção e restauração. Seu poder cresce quando usado para sustentar outros.", story: "Aurea ouviu Aurenya uma única vez: um sussurro entre dois amanheceres. Desde então segue o rastro de uma pena dourada que jamais toca o chão." },
  { name: "Centauro", slug: "centauro", title: "Lança do horizonte", affinity: "Vento", stats: { hp: 105, atk: 80, def: 65, arcDef: 45, speed: 55, arcana: 30 }, bonuses: ["+10% Velocidade", "+5% Ataque Físico", "+5% Resistência Física"], penalties: ["−10% Defesa Arcana", "−5% Velocidade em interiores"], description: "Guerreiros nômades de grande impacto e mobilidade. Em campo aberto, sua carga decide batalhas antes do segundo golpe.", story: "Kael percorre Luminária com uma lança marcada por sete pactos. O oitavo só poderá ser firmado diante do deus esquecido de Nozkar." },
  { name: "Demônio", slug: "demonio", title: "Herdeiro do eclipse", affinity: "Sombra", stats: { hp: 95, atk: 85, def: 50, arcDef: 50, speed: 50, arcana: 50 }, bonuses: ["+5% Ataque", "+5% Dano Sombrio", "+5% Defesa Arcana"], penalties: ["−10% Defesa Física"], description: "Marcados pela energia do abismo, demônios convertem risco em poder ofensivo. Muitos lutam para provar que origem não é destino.", story: "Nahir arrancou o próprio nome do livro do culto. Cada batalha apaga mais uma corrente, mas aproxima o dia em que Nozkar perceberá a traição." },
  { name: "Draconiano", slug: "draconiano", title: "Sangue da primeira chama", affinity: "Fogo", stats: { hp: 120, atk: 65, def: 95, arcDef: 45, speed: 25, arcana: 30 }, bonuses: ["+10% Defesa Física", "+5% Defesa Arcana", "Resiste a fogo"], penalties: ["−10% Arcana", "Vulnerável a gelo"], description: "Herdeiros de uma linhagem ancestral, combinam escamas impenetráveis e sopro elemental. São lentos, mas difíceis de deter.", story: "Rhaz dormiu cem anos sob Azhar. Ao acordar, encontrou o brasão de seu clã nas mãos de saqueadores e jurou recuperá-lo sem incendiar os inocentes." },
  { name: "Elfo", slug: "elfo", title: "Flecha do bosque", affinity: "Natureza", stats: { hp: 80, atk: 70, def: 50, arcDef: 55, speed: 85, arcana: 40 }, bonuses: ["+5% Velocidade", "+5% Crítico", "+5% Precisão"], penalties: ["−10% Defesa Física"], description: "Ágeis observadores ligados aos ciclos naturais. Atacam antes que o adversário perceba a mudança do vento.", story: "Elarin é o último a lembrar o nome original da árvore colossal. Se pronunciá-lo, poderá curar D’Akan — ou despertar aquilo que suas raízes aprisionam." },
  { name: "Espectro", slug: "espectro", title: "Eco sem descanso", affinity: "Abismo", stats: { hp: 95, atk: 60, def: 55, arcDef: 45, speed: 70, arcana: 55 }, bonuses: ["+10% Dano Arcano", "+5% Velocidade", "+10% Resistência a controle"], penalties: ["−10% Defesa Arcana", "−10% Resistência à luz"], description: "Almas que recusaram o último passo. Atravessam defesas e carregam memórias que não lhes pertencem.", story: "Vel conhece todas as portas de Nozkar porque morreu atrás de cada uma delas. Agora busca o corpo que ainda sonha em algum lugar do vale." },
  { name: "Fada", slug: "fada", title: "Centelha feérica", affinity: "Luz", stats: { hp: 80, atk: 50, def: 45, arcDef: 70, speed: 60, arcana: 75 }, bonuses: ["+10% Arcana", "+5% Velocidade", "+5% Cura realizada"], penalties: ["−10% Vida", "−5% Defesa Física"], description: "Pequenos seres de grande potência arcana. Alteram o campo com bênçãos, ilusões e caprichos perigosamente belos.", story: "Miri roubou uma gota da Primeira Aurora para salvar sua aldeia. O brilho ainda vive em suas asas e atrai tanto peregrinos quanto monstros." },
  { name: "Fera", slug: "fera", title: "Caçador da lua", affinity: "Sangue", stats: { hp: 100, atk: 80, def: 60, arcDef: 40, speed: 65, arcana: 35 }, bonuses: ["+10% Velocidade", "+5% Ataque Físico", "+5% Roubo de vida"], penalties: ["−10% Defesa Arcana", "−5% Resistência a controle"], description: "Predadores guiados por instinto e lealdade de matilha. Quanto mais próximo o perigo, mais feroz se torna sua resposta.", story: "Kora perdeu a matilha para uma névoa que caminhava contra o vento. Ela caça a criatura desde então, deixando marcas de prata para nunca perder o caminho de volta." },
  { name: "Gnomo", slug: "gnomo", title: "Artífice impossível", affinity: "Arcana", stats: { hp: 85, atk: 50, def: 50, arcDef: 65, speed: 55, arcana: 75 }, bonuses: ["+10% Arcana", "+5% Precisão", "+5% Velocidade"], penalties: ["−10% Vida", "−5% Ataque Físico"], description: "Inventores inquietos que misturam mecanismos e magia. Uma preparação inteligente faz deles adversários imprevisíveis.", story: "Pim construiu uma bússola que aponta para problemas. Ela nunca parou de girar desde que ele chegou ao quadro de missões da guilda." },
  { name: "Goblin", slug: "goblin", title: "Príncipe dos atalhos", affinity: "Sorte", stats: { hp: 75, atk: 60, def: 45, arcDef: 50, speed: 85, arcana: 65 }, bonuses: ["+10% Velocidade", "+5% Ouro", "+5% Esquiva"], penalties: ["−10% Vida", "−5% Defesa Física"], description: "Oportunistas velozes, engenhosos e difíceis de cercar. Sempre encontram uma saída — ou inventam uma.", story: "Zik comprou por engano um mapa do tesouro que só aparece quando molhado. O problema é que o X se move toda vez que ele olha para outro lado." },
  { name: "Humano", slug: "humano", title: "Portador de escolhas", affinity: "Aurora", stats: { hp: 95, atk: 70, def: 65, arcDef: 65, speed: 45, arcana: 40 }, bonuses: ["+10% Experiência", "+5% Resistências", "+5% Ouro"], penalties: ["−10% Vida"], description: "Adaptáveis e ambiciosos, humanos prosperam em qualquer caminho. Sua maior força é transformar derrota em aprendizado.", story: "Lys foi recusado por três ordens e aceito por uma espada sem dono. O metal não fala, mas vibra sempre que um Fragmento da Aurora está perto." },
  { name: "Marionete", slug: "marionete", title: "Alma costurada", affinity: "Runas", stats: { hp: 95, atk: 65, def: 60, arcDef: 65, speed: 50, arcana: 45 }, bonuses: ["+10% Resistência a controle", "+5% Defesa Arcana", "+5% Precisão"], penalties: ["−10% Cura recebida", "−5% Vida"], description: "Corpos artificiais animados por runas e memórias. Resistentes a manipulação, buscam respostas sobre quem os criou.", story: "Sete carrega no peito uma caixinha de música com a voz de sua criadora. Falta a última nota, escondida numa oficina soterrada em Luminária." },
  { name: "Oni", slug: "oni", title: "Punho da tempestade", affinity: "Trovão", stats: { hp: 130, atk: 95, def: 70, arcDef: 35, speed: 25, arcana: 25 }, bonuses: ["+10% Vida", "+5% Ataque Físico", "+5% Resistência a controle"], penalties: ["−10% Defesa Arcana", "−5% Velocidade"], description: "Colossos de força brutal e vontade obstinada. Cada golpe é uma promessa de que o combate não terminará facilmente.", story: "Goro jurou nunca mais erguer o porrete por raiva. A promessa será testada quando encontrar o general que transformou sua aldeia em cinzas." },
  { name: "Sereiano", slug: "sereiano", title: "Voz das marés", affinity: "Água", stats: { hp: 95, atk: 55, def: 50, arcDef: 70, speed: 45, arcana: 65 }, bonuses: ["+10% Velocidade aquática", "+5% Defesa Arcana", "+5% Cura recebida"], penalties: ["−10% Defesa Física", "−20% Velocidade em terra"], description: "Habitantes de Thalenn que moldam água e canto. Dentro do mar são incomparáveis; em terra dependem de astúcia e magia.", story: "Naia escuta sinos no fundo do oceano. Cada toque faz uma ilha desaparecer, e ela teme que o próximo leve consigo toda a costa." },
  { name: "Slime", slug: "slime", title: "Forma mutável", affinity: "Ácido", stats: { hp: 115, atk: 55, def: 75, arcDef: 50, speed: 35, arcana: 50 }, bonuses: ["+10% Resistência Física", "+5% Regeneração", "+5% Resistência a controle"], penalties: ["−10% Dano Físico", "−5% Velocidade"], description: "Organismos adaptáveis capazes de absorver impactos e alterar a própria forma. Vencem por persistência e surpreendente inteligência.", story: "Glim nasceu em um frasco de alquimista e aprendeu o mundo copiando gestos. Agora quer descobrir por que reconhece ruínas milenares que nunca visitou." },
  { name: "Vampiro", slug: "vampiro", title: "Nobre da noite", affinity: "Sangue", stats: { hp: 95, atk: 80, def: 55, arcDef: 55, speed: 60, arcana: 35 }, bonuses: ["+10% Roubo de vida", "+5% Velocidade", "+5% Crítico"], penalties: ["−10% Resistência à luz", "−5% Cura recebida"], description: "Predadores elegantes que renovam a própria força ao ferir o inimigo. A luz revela a fragilidade por trás de sua presença imponente.", story: "Vesper protege uma cidade que acredita tê-lo executado. Das torres, caça em segredo os verdadeiros monstros que chegam quando o sol se põe." },
  { name: "Zumbi", slug: "zumbi", title: "O que voltou", affinity: "Ruína", stats: { hp: 110, atk: 70, def: 65, arcDef: 60, speed: 35, arcana: 40 }, bonuses: ["Imune a sangramento", "Imune a veneno", "+5% Roubo de vida"], penalties: ["−10% Defesa Física", "−5% Cura recebida"], description: "Mortos que conservaram vontade e propósito. Dor, doença e medo já não os detêm, embora fogo e luz ainda cobrem seu preço.", story: "Orun acordou segurando um selo de guilda lendário e sem memória. Cada missão concluída devolve um rosto — nenhum deles parece ser o seu." },
];

export const regions = [
  { name: "Planalto de Luminária", slug: "planalto-de-luminaria", role: "Centro social e econômico", size: "4.800 km²", danger: "Moderado", lore: "Campos dourados, colinas e a capital erguida sobre ruínas subterrâneas. Guildas prosperam enquanto um culto procura a passagem secreta para Nozkar." },
  { name: "Floresta D’Akan", slug: "floresta-dakan", role: "Exploração e sobrevivência", size: "18.000 km²", danger: "Alto", lore: "Um labirinto vivo de névoa, árvores colossais e caminhos instáveis. Espíritos guardam santuários enquanto um ancestral corrompido desperta sob as raízes." },
  { name: "Costa de Thalenn", slug: "costa-de-thalenn", role: "Tesouros e aventura marítima", size: "45.000 km²", danger: "Alto", lore: "Recifes, cavernas submersas, navios abandonados e ilhas que mudam de lugar. Algo enorme responde aos sinos do fundo do mar." },
  { name: "Deserto de Azhar", slug: "deserto-de-azhar", role: "Ruínas ancestrais", size: "30.000 km²", danger: "Severo", lore: "Dunas infinitas, cânions vermelhos e oásis perdidos. Tempestades revelam templos soterrados e o colosso de areia que os protege." },
  { name: "Montanhas de Kragor", slug: "montanhas-de-kragor", role: "Mineração e combate", size: "28.800 km²", danger: "Severo", lore: "Picos congelados, minas abandonadas e vulcões adormecidos. Cristais arcanos raros alimentam a antiga fortaleza anã e seu titã de pedra." },
  { name: "Vale Sombrio de Nozkar", slug: "vale-sombrio-de-nozkar", role: "História principal", size: "75.000 km²", danger: "Extremo", lore: "Florestas mortas e pântanos negros cercam o templo do deus esquecido. A corrupção evolui, os inimigos aprendem e o selo enfraquece." },
];

export const statLabels = { hp: "Vida", atk: "Ataque", def: "Defesa", arcDef: "Def. Arcana", speed: "Velocidade", arcana: "Arcana" } as const;
